version: '2'
services:
    authenticator-app:
        image: authenticator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://authenticator-postgresql:5432/authenticator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    authenticator-postgresql:
        extends:
            file: postgresql.yml
            service: authenticator-postgresql
